name: 'Lint Julia code for formatting'
description: 'A Julia code format linter based on DocumentFormat.jl'
author: 'David Anthoff'

branding:
  icon: 'eye'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: julia --color=yes -e 'using Pkg; Pkg.activate("juliaformatlinter", shared=true); Pkg.add(["DocumentFormat", "FilePaths"]); using DocumentFormat, FilePaths; exit(DocumentFormat.isformatted(p".") ? 0 : 1)'
      shell: bash
